server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"          # 注意引号
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: mini_calling
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.dking.mini_calling.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 上线前删
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  expiration: 86400000
  header: Authorization
  prefix: "Bearer "

logging:
  level:
    com.dking.mini_calling: debug
    org.springframework.security: DEBUG
